# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-62394ebf-71fd-4fd4-93ee-08fba6678afd";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-62394ebf-71fd-4fd4-93ee-08fba6678afd".device = "/dev/disk/by-uuid/62394ebf-71fd-4fd4-93ee-08fba6678afd";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1FD4-8E21";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
